server:
  port: 9090
  servlet:
    context-path: /api
    multipart:
      max-file-size: 1024KB
      max-request-size: 1024KB

spring:
  config:
    import: optional:env.properties
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  mail:
    default-encoding: UTF-8
    host: smtp.office365.com
    port: 587
    username: ${EMAIL}
    password: ${EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    protocol: smtp
    test-connection: false
  profiles:
    active: dev

cloudinary:
  CLOUD_NAME: ${CLOUD_NAME}
  API_SECRET: ${API_SECRET}
  API_KEY: ${API_KEY}

values:
  SECRET_KEY: 721bae22437679240e714b573f8991f569138758dc88616214ae1edb77d4129b
  DEFAULT_PROFILE_PICTURE: https://res.cloudinary.com/def8hdamv/image/upload/v1701453504/barber-app/qnnolu3m8se0zqe5rilq.png